/**
 * Chronicle API (Hono)
 *
 * Handles telemetry endpoints mounted at /api/v1/*
 * Built with Hono + Drizzle ORM + Cloudflare D1.
 */

import { Hono } from "hono";
import { cors } from "hono/cors";
import { logger } from "hono/logger";
import { prettyJSON } from "hono/pretty-json";
import { telemetry } from "./routes/telemetry";

// CloudflareBindings is auto-generated by `wrangler types`
const app = new Hono<{ Bindings: CloudflareBindings }>();

// ============================================================================
// Middleware
// ============================================================================

// CORS - allow requests from anywhere (CLI tool)
app.use(
  "*",
  cors({
    origin: "*",
    allowMethods: ["GET", "POST", "OPTIONS"],
    allowHeaders: ["Content-Type", "Authorization"],
  }),
);

// Pretty JSON in development
app.use("*", prettyJSON());

// Request logging (disable in production if too noisy)
app.use("*", logger());

// ============================================================================
// Routes
// ============================================================================

// API root
app.get("/", (c) => {
  return c.json({
    name: "Chronicle API",
    version: "1.0.0",
    endpoints: {
      track: "POST /api/v1/track",
      batch: "POST /api/v1/batch",
      health: "GET /api/v1/health",
      stats: "GET /api/v1/stats",
    },
  });
});

// Mount telemetry routes under /v1
app.route("/v1", telemetry);

// 404 handler
app.notFound((c) => {
  return c.json({ error: "Not found" }, 404);
});

// Error handler
app.onError((err, c) => {
  console.error("Unhandled error:", err);
  return c.json({ error: "Internal server error" }, 500);
});

export default app;
